language: node_js
node_js:
  - '12'
  - '10'

before_install:
  - sudo apt-get install -y autoconf automake libtool

install:
  - wget https://github.com/protocolbuffers/protobuf/archive/v3.10.0.tar.gz
  - tar -xzvf v3.10.0.tar.gz
  - pushd protobuf-3.10.0 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install && popd
  - wget https://github.com/grpc/grpc-web/archive/1.0.6.tar.gz
  - tar -xzvf 1.0.6.tar.gz
  - pushd grpc-web-1.0.6 && sudo make install-plugin && popd
